title: Yunus Abdulazis # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Statistics Undergraduate Student at Diponegoro University
  <br>
  Data Warehousing, Analysis, and Visualization for Business Insights
  <br>
  Semarang, Jawa Tengah, Indonesia
  <br><br><br>
  <a href="https://www.linkedin.com/in/yunus-abdulazis-3375071b5/">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.instagram.com/abdyunuss/">View My Instagram Profile</a>
